[project]
name = "tinybfv"
version = "0.1.0"
description = "BFV implementation in tinygrad"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.9.10",
    "tinygrad>=0.10.2",
]
